const COUNTRY_FLAGS: Record<string, string> = {
  "United States": "🇺🇸",
  "United Kingdom": "🇬🇧",
  "Canada": "🇨🇦",
  "Australia": "🇦🇺",
  "Ireland": "🇮🇪",
  "New Zealand": "🇳🇿",
  "South Africa": "🇿🇦",
  "Spain": "🇪🇸",
  "Mexico": "🇲🇽",
  "Argentina": "🇦🇷",
  "Colombia": "🇨🇴",
  "Chile": "🇨🇱",
  "Peru": "🇵🇪",
  "Venezuela": "🇻🇪",
  "Uruguay": "🇺🇾",
  "Paraguay": "🇵🇾",
  "Bolivia": "🇧🇴",
  "Ecuador": "🇪🇨",
  "Cuba": "🇨🇺",
  "Dominican Republic": "🇩🇴",
  "Puerto Rico": "🇵🇷",
  "Costa Rica": "🇨🇷",
  "Panama": "🇵🇦",
  "Guatemala": "🇬🇹",
  "Honduras": "🇭🇳",
  "El Salvador": "🇸🇻",
  "Nicaragua": "🇳🇮",
  "Brazil": "🇧🇷",
  "Portugal": "🇵🇹",
  "France": "🇫🇷",
  "Germany": "🇩🇪",
  "Italy": "🇮🇹",
  "Netherlands": "🇳🇱",
  "Belgium": "🇧🇪",
  "Switzerland": "🇨🇭",
  "Austria": "🇦🇹",
  "Sweden": "🇸🇪",
  "Norway": "🇳🇴",
  "Denmark": "🇩🇰",
  "Finland": "🇫🇮",
  "Iceland": "🇮🇸",
  "Poland": "🇵🇱",
  "Czech Republic": "🇨🇿",
  "Slovakia": "🇸🇰",
  "Hungary": "🇭🇺",
  "Romania": "🇷🇴",
  "Bulgaria": "🇧🇬",
  "Greece": "🇬🇷",
  "Turkey": "🇹🇷",
  "Russia": "🇷🇺",
  "Ukraine": "🇺🇦",
  "Belarus": "🇧🇾",
  "Lithuania": "🇱🇹",
  "Latvia": "🇱🇻",
  "Estonia": "🇪🇪",
  "Croatia": "🇭🇷",
  "Serbia": "🇷🇸",
  "Slovenia": "🇸🇮",
  "Bosnia and Herzegovina": "🇧🇦",
  "Albania": "🇦🇱",
  "Ireland ": "🇮🇪",
  "China": "🇨🇳",
  "Japan": "🇯🇵",
  "South Korea": "🇰🇷",
  "North Korea": "🇰🇵",
  "India": "🇮🇳",
  "Pakistan": "🇵🇰",
  "Bangladesh": "🇧🇩",
  "Sri Lanka": "🇱🇰",
  "Nepal": "🇳🇵",
  "Thailand": "🇹🇭",
  "Vietnam": "🇻🇳",
  "Philippines": "🇵🇭",
  "Indonesia": "🇮🇩",
  "Malaysia": "🇲🇾",
  "Singapore": "🇸🇬",
  "Hong Kong": "🇭🇰",
  "Taiwan": "🇹🇼",
  "Cambodia": "🇰🇭",
  "Laos": "🇱🇦",
  "Myanmar": "🇲🇲",
  "Mongolia": "🇲🇳",
  "Kazakhstan": "🇰🇿",
  "Uzbekistan": "🇺🇿",
  "Saudi Arabia": "🇸🇦",
  "United Arab Emirates": "🇦🇪",
  "Qatar": "🇶🇦",
  "Kuwait": "🇰🇼",
  "Bahrain": "🇧🇭",
  "Oman": "🇴🇲",
  "Yemen": "🇾🇪",
  "Iraq": "🇮🇶",
  "Iran": "🇮🇷",
  "Israel": "🇮🇱",
  "Palestine": "🇵🇸",
  "Jordan": "🇯🇴",
  "Lebanon": "🇱🇧",
  "Syria": "🇸🇾",
  "Egypt": "🇪🇬",
  "Morocco": "🇲🇦",
  "Algeria": "🇩🇿",
  "Tunisia": "🇹🇳",
  "Libya": "🇱🇾",
  "Sudan": "🇸🇩",
  "Nigeria": "🇳🇬",
  "Kenya": "🇰🇪",
  "Ethiopia": "🇪🇹",
  "Ghana": "🇬🇭",
  "Tanzania": "🇹🇿",
  "Uganda": "🇺🇬",
  "Rwanda": "🇷🇼",
  "Senegal": "🇸🇳",
  "Ivory Coast": "🇨🇮",
  "Cameroon": "🇨🇲",
  "Zimbabwe": "🇿🇼",
  "Zambia": "🇿🇲",
  "Angola": "🇦🇴",
  "Mozambique": "🇲🇿",
};

export function countryFlag(country?: string | null): string {
  if (!country) return "";
  const trimmed = country.trim();
  if (COUNTRY_FLAGS[trimmed]) return COUNTRY_FLAGS[trimmed];
  // Try case-insensitive match
  const key = Object.keys(COUNTRY_FLAGS).find(
    (k) => k.toLowerCase() === trimmed.toLowerCase()
  );
  return key ? COUNTRY_FLAGS[key] : "";
}